name: 'Jira Transition on PR Merge'
description: 'Transitions a Jira issue to QA when a PR is merged into develop by extracting the Jira link from the PR body.'
author: 'Your Name or Org'

runs:
  using: 'composite'
  steps:
    - name: Extract Jira Ticket ID and Transition
      shell: bash
      run: ./scripts/transitions.sh

branding:
  icon: 'repeat'
  color: 'blue'
